name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./namnam/namnam.sln
    - name: Build
      run: dotnet build --no-restore ./namnam/namnam.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./namnam/namnam.sln
    - name: Publish
      run: dotnet publish ./namnam/namnam/namnam.csproj
    - name: Easy Zip Files
      uses: vimtor/action-zip@v1
      with:
        files: ./namnam/namnam/bin/Debug/net5.0/publish/
        recursive: false
        dest: result.zip
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/result.zip
